import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../database/prisma.service';
import { CreateLanguageDto } from './dto/create-language.dto';
import { TranslationService } from '../../common/services/translation.service';

@Injectable()
export class LanguagesService {
  constructor(
    private prisma: PrismaService,
    private translationService: TranslationService,
  ) {}

  /**
   * Dịch văn bản thuyết minh và lưu vĩnh viễn vào DB (Public)
   */
  async translateText(text: string, targetLangCode: string, storeId?: string) {
    if (!targetLangCode) return { translatedText: '' };

    // 1. Tìm ngôn ngữ mục tiêu
    const language = await this.prisma.language.findUnique({
      where: { code: targetLangCode },
    });
    if (!language) throw new NotFoundException(`Ngôn ngữ "${targetLangCode}" không hỗ trợ`);

    // 2. Nếu có storeId, kiểm tra xem đã có bản dịch trong DB chưa
    if (storeId) {
      const existing = await this.prisma.narration.findUnique({
        where: {
          storeId_languageId: {
            storeId,
            languageId: language.id,
          },
        },
        include: { language: true },
      });
      if (existing) return existing;
    }

    // 3. Nếu chưa có hoặc không có storeId, thực hiện dịch
    let sourceText = text;
    
    // Nếu có storeId mà text truyền lên trống, cố gắng lấy bản gốc từ DB
    if (storeId && !sourceText) {
      const sourceNarration = await this.prisma.narration.findFirst({
        where: { storeId, language: { code: 'vi' } },
      });
      sourceText = sourceNarration?.textContent;
    }

    if (!sourceText) return { textContent: '', message: 'Không tìm thấy nội dung gốc để dịch', language };

    const result = await this.translationService.translate(sourceText, 'vi', targetLangCode);

    // 4. Nếu có storeId, lưu bản dịch này vào DB luôn
    if (storeId) {
      return this.prisma.narration.create({
        data: {
          storeId,
          languageId: language.id,
          textContent: result.translatedText,
          isActive: true,
        },
        include: { language: true },
      });
    }

    return {
      textContent: result.translatedText,
      language,
      isAutoGenerated: true,
    };

  }



  /**
   * Lấy danh sách tất cả ngôn ngữ đang hoạt động
   */
  async findAll() {
    return this.prisma.language.findMany({
      where: { isActive: true },
      orderBy: { name: 'asc' },
    });
  }

  /**
   * Lấy chi tiết ngôn ngữ theo ID, kèm số lượng narrations
   */
  async findOne(id: string) {
    const language = await this.prisma.language.findUnique({
      where: { id },
      include: {
        _count: { select: { narrations: true } },
      },
    });
    if (!language) throw new NotFoundException('Ngôn ngữ không tồn tại');
    return language;
  }

  /**
   * Tìm ngôn ngữ theo code (vd: 'vi', 'en', 'ja')
   */
  async findByCode(code: string) {
    const language = await this.prisma.language.findUnique({
      where: { code },
    });
    if (!language) throw new NotFoundException(`Ngôn ngữ "${code}" không tồn tại`);
    return language;
  }

  create(dto: CreateLanguageDto) {
    return this.prisma.language.create({
      data: dto,
    });
  }

  update(id: string, dto: Partial<CreateLanguageDto>) {
    return this.prisma.language.update({
      where: { id },
      data: dto,
    });
  }

  remove(id: string) {
    return this.prisma.language.delete({
      where: { id },
    });
  }
}
